name: Build and Push MkDocs Site

on:
  push:
    branches:
      - '**'  # All branches

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/supremedental-mainhub


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set tag
      run: echo "BRANCH_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: mkdocs/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ env.BRANCH_TAG }}

    # - name: Run run.sh on DigitalOcean server
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.DIGITALOCEAN_HOST }}
    #     username: ${{ secrets.DIGITALOCEAN_USER }}
    #     key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
    #     script: |
    #       cd /tmp/
    #       chmod +x run.sh
    #       ./run.sh

    - name: SSH into server and run script
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ahsaniqbal
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        port: 22
        script: |
          echo "✅ Connected successfully!"
          cd /tmp/
          chmod +x run.sh
          ./run.sh
        timeout: 1800s
        command_timeout: 900s
        debug: true


