name: Build and Push MkDocs Site

on:
  push:
    branches:
      - '**'  # All branches

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/supremedental-mainhub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set tag
        run: echo "BRANCH_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: mkdocs/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.BRANCH_TAG }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Authenticate cloudflared
        run: |
          mkdir -p ~/.cloudflared
          echo '${{ secrets.CLOUDFLARED_CERT }}' > ~/.cloudflared/cert.pem

      - name: Create dummy file on remote via cloudflared
        run: |
          ssh -o StrictHostKeyChecking=no -o ProxyCommand="cloudflared access ssh --hostname %h" ahsaniqbal@ssh.ocooee.com 'bash /tmp/run.sh'


      


