name: Build and Push MkDocs Site

on:
  push:
    branches:
      - '**'  # All branches

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/supremedental-mainhub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Set tag
      #   run: echo "BRANCH_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build & push image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: mkdocs/Dockerfile
      #     push: true
      #     tags: |
      #       ${{ env.IMAGE_NAME }}:latest
      #       ${{ env.IMAGE_NAME }}:${{ env.BRANCH_TAG }}


      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Add SSH config with ProxyCommand
        run: |
          mkdir -p ~/.ssh
          echo "Host ssh.ocooee.com
            User ahsaniqbal
            ProxyCommand cloudflared access ssh --hostname %h
            IdentityFile ~/.ssh/ahsaniqbal_id_rsa" >> ~/.ssh/config

      - name: Run SSH command
        run: |
          ssh ssh.ocooee.com "echo 'Hello from GitHub!'"
        env:
          CLOUDFLARED_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

      
      
      # - name: Remote SSH Command
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ssh.ocooee.com
      #     username: ahsaniqbal
      #     key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
      #     script: |
      #       echo "Deploying something..."
      #     ssh_options: "-4" # ✅ Forces IPv4 usage


